### ISSUE TITLE
Needed to run each command a couple times

### ISSUE THREAD

**Issue by mike-luabase** [lucasmerlin/hurlurl#1]
Thanks for publishing this, excellent real world example.

It might help others to know you need to run all of the `yarn` commands a couple times for this to fully start up. I was getting the error:

```
error: proc macro panicked
  --> urllb/src/main.rs:40:30
   |
40 | static STATIC_DIR: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/../web/dist");
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: "/Users/mritchie712/blackbird/hurlurl/urllb/../web/dist" is not a directory
```

When trying to start the backend, but it went away after rerunning each command.

**Comment by lucasmerlin** [comment]
Thanks for testing this out! I clarified the instructions in the readme
