### ISSUE TITLE
Being used by spammers

### ISSUE THREAD

**Issue by KTibow** [lucasmerlin/hurlurl#2]
For example, phishing spam was sent out via the URL `https://hurlurl.com/4d7xI`.

**Comment by inkitori** [comment]
Same with `https://hurlurl.com/info/N4XNZ`

**Comment by piprett** [comment]
Steam phishing `hxxps[://]hurlurl[.]com/info/elfAH`

**Comment by lucasmerlin** [comment]
Hi, thanks for letting me know! I've marked these as fraudulent, meaning anyone clicking any of these links will see a message that it's a scam and I've also blacklisted any new urls from being created that contain the word "steam". Any more ideas how I could prevent scams like this in the future?

**Comment by Hyperion60** [comment]
I found another `https[://]hurlurl.com/9nx6M`, thanks to Discord mod bot to block this.

**Comment by lucasmerlin** [comment]
I've decided to make hurlurl paid, meaning you will now need to pay 1€ for each created short link. I hope this is enough to discourage scammers from using it lol. Curious if anyone will ever purchase a link haha.

I hope this is enough to stop the spam. Please open a new issue if any more spam comes up.
