### ISSUE TITLE
Scam sent from https://hurlurl.com/9nx6M

### ISSUE THREAD

**Issue by Supernova3339** [lucasmerlin/hurlurl#3]
Hi, a scam link was sent from here. https://hurlurl.com/9nx6M

I would strongly suggest checking links with virustotal and having certain keymatches

eg steamcommunity.com would work, but steumcommunity.com would not work

**Comment by lucasmerlin** [comment]
Thank you for reporting! I marked it as fraud, and also since there were many more reports (by email and via #2) I've decided to introduce a paywall (1€) to create a link. While I'd like hurlurl to remain free this seems like a easy way to combat spam.
